name: CombatTag
version: 1.2.4
authors: [cheddar262, Omnivion, Exloki]
main: com.trc202.CombatTag.CombatTag
website: https://github.com/Curspex/Combat-Tag-INSTAKILL
description: Prevent players from logging out in combat
commands:
  CombatTag:
    description: Shows the current remaining time in a tag
    aliases: ct
    usage: /ct, /ct check <player>