name: CombatTag
version: 1.1.4
authors: [cheddar262, Omnivion]
main: com.trc202.CombatTag.CombatTag
dev-url: https://github.com/Curspex/Combat-Tag-INSTAKILL
commands:
  CombatTag:
    description: Shows the current remaining time in a tag
    aliases: ct
    usage: /ct, /ct check <player>